import assert from 'node:assert/strict';
import { api, post, setCSRF, readPage } from './src/api.js';
const originalTimer=globalThis.setTimeout;
globalThis.setTimeout=(fn)=>originalTimer(fn,5);
let calls=0;
globalThis.fetch=async (_,options)=>{calls++;return {ok:true,json:()=>new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))))};};
await assert.rejects(post('action',{requestId:'fixed'}),/不会自动重试/);
assert.equal(calls,1,'Timeout must never resend');
globalThis.fetch=async()=>({ok:false,status:401,json:async()=>({error:'登录失效'})});
await assert.rejects(api('session'),error=>error.status===401);
setCSRF('test-csrf');
globalThis.fetch=async (_,options)=>{assert.equal(options.headers['X-CSRF-Token'],'test-csrf');return {ok:true,json:async()=>({delivery:'accepted'})};};
assert.equal((await post('action',{})).delivery,'accepted');
let pageCalls = 0, stages = [];
globalThis.fetch = async () => ({ok:true, json:async()=> ++pageCalls < 3 ? {loading:true} : {turns:['ready']}});
assert.deepEqual(await readPage('tasks/1/history', {waiting: s => stages.push(s)}), {turns:['ready']});
assert.equal(pageCalls, 3); assert.equal(stages.length, 2);
globalThis.fetch = async () => ({ok:true,json:async()=>({error:'可重试的读取失败'})});
await assert.rejects(readPage('tasks/1/history'), /可重试/);
pageCalls=0; globalThis.fetch=async()=>{pageCalls++;throw new Error('must not fetch unmounted thread');};
assert.equal(await readPage('tasks/1/history', {alive:()=>false}), null); assert.equal(pageCalls,0);
globalThis.fetch=async()=>({ok:true,json:async()=>({loading:true})});
await assert.rejects(readPage('tasks/1/history', {timeout:-1}), /读取较慢/);
globalThis.setTimeout=originalTimer;
console.log('PASS: timeout during body read, no automatic resend, auth status propagation, CSRF retained, read-only polling, cancellation and bounded waiting');
